### ISSUE TITLE
October 25 - 29

### ISSUE THREAD

**Issue by sarenaz** [sarenaz/Frictionless-Fellowship#2]
- [x] - Creation of a roadmap (follow this [lesson](http://fellows.frictionlessdata.io/lessons/#journalclub))
- [x] - Discuss the journal club article during the group meeting
- [x] - *Check in*: Group meeting
